travis:
  secure:
    BINSTAR_TOKEN: ApyRxipObdqauaMxS5mxgPXaWfnES3EbPe6mz0kVpwGwDtUyyjIuYTWhxLEs5l9+p9w8nDtkyun810i8kzf+kJS4H21gDiwLSJFV5EdHMIPFUJH80gfANb30ZG3vTpH2GpNBMRC4b+ravcvFzYFW7LMyM0nheHzHeoXIyR8n4XOveu/ZqKi6miLYWZE/bfrlLoWbMS2HnDcMg0hdPAolnBWfKi2UTPtYPv9REqfQi5preFo1UWjT5tlXnT1xI0u1EMCodjEHRW1XPGRpHkA2QIBQ5AJ113/nePFZ9tPmuKYTVwurgstLhHZx+WZTG+1FRhb3Ycrk0fMAwVr1MRE7t6+daiSTkrf2FXU2xajXkeX3YE71etAfoZCSz26M2PAvgCITtm2vs1uoD8MQQcniLhjaZsij3eUU9BriI9/ebL2QZ4kQl07lL7buLsvO72uCfGjcqAs4qocgh0pQkJvUwn1iV5neySLBHMzqqjacmOw6l4LAVjenATuEhcXuMB89XcaFHxhyY8stxgJS7R3qyzOR9cYXsp5cKP4n5IPwPdK1eDReRAaAnLe9b1VPynD8g+DNtYrWafEYsgBFvXVQrKYVjCJvhykMuhiL5WCJXGzmM66BWjtLOU552d6VJs/SBI0/fcRZoMYUB1zWMU2GWm74d2BkQ9V0YIwVuYE9OXc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
